---
#
# vars file for mq_backup
# You can configure according to your Firm requirements
#
mq_bkup_bin: '/opt/mqm/bin/dmpmqcfg'
mq_bkup_file_prefix: 'Obj_Auth_Bkup'
mq_dump_wait_time: 120

mq_status_file_loc: '/tmp'
mq_status_file_prefix: 'mqbackup'

bkup_retention: 4w

varmqmqmgrs: '/var/mqm/qmgrs'
