---
 #
 # Ansible Playbook Pakcage for taking Queue Manager backup
 #
 # 1) Takes Queue Manager backup and save it on Managed node and Ansible local node (2 way copies of the same backup)
 # 2) Manages old backup files as per retention value 
 # 3) Fetches all the backup status and host unreachable files to ansible local nodes
 # 4) Send as backup status report on an email 
 #
 # Version: 1.0
 # Author: Vignesh Sundararaman
 #
 - name: Playbook for taking Queue Manager Object Backup
   hosts: "{{ HOST }}"
   gather_facts: no
   serial: 1
   tasks:
     - name: Clean up previous status files
       file:
         path: "/tmp/bkup_status.txt"
         state: absent
       run_once: yes
       delegate_to: localhost

     - name: Do ping test first
       ping:
       register: ping_result
       ignore_unreachable: true

     - name: display debug result
       delegate_to: localhost
       debug:
         msg: "{{ ping_result }}"
         - name: write server unreachable failure for Qmgr Host
           lineinfile:
              path: '{{ mq_status_file_loc }}/{{ mq_status_file_prefix }}_{{ QmgrName }}_failure.txt'
              line: "{{ QmgrName }}/-1/Host Unavailable, Backup process failed"
              create: yes
              mode: '0644'
       when:
         - "'unreachable' in ping_result"
       delegate_to: localhost
       
     #
     # Block for Taking Backup for DEV Qmgrs
     #
     - block:
         - name: Getting Queue DEV Manager
           set_fact:
              qm: {{ QMgrName }}

         - name: Print the DEV Queue Manager
           debug:
             msg: "{{ qm }}"

         - name: Prepare and Take MQ Backup for the DEV QMgr
           include_role:
              name: mqbkup_qmgr
           vars:
              qmgr: "{{ qm }}"
              env: "DEV"
       when:
         - "'unreachable' not in ping_result"
         - "'DEV' in group_names"

     #
     # Block for Taking Backup for QA Qmgrs
     #
     - block:
         - name: Getting QA Queue Manager
           set_fact:
              qm: {{ QMgrName }}

         - name: Print the QA Queue Manager
           debug:
             msg: "{{ qm }}"

         - name: Prepare and Take MQ Backup for the QA QMgr
           include_role:
              name: mqbkup_qmgr
           vars:
              qmgr: "{{ qm }}"
              env: "QA"
       when:
         - "'unreachable' not in ping_result"
         - "'QA' in group_names"

     #
     # Block for Taking Backup for PROD Qmgrs
     #
     - block:
         - name: Getting PROD Queue Manager
           set_fact:
              qm: {{ QMgrName }}

         - name: Print the PROD Queue Manager
           debug:
             msg: "{{ qm }}"

         - name: Prepare and Take MQ Backup for the PROD QMgr
           include_role:
              name: mqbkup_qmgr
           vars:
              qmgr: "{{ qm }}"
              env: "PROD"
       when:
         - "'unreachable' not in ping_result"
         - "'PROD' in group_names"
     

- name: Playbook for consolidating status file in ansible node and send email
   hosts: localhost
   gather_facts: no
   serial: 1
   tasks:
     #
     # Now Merge all the output backup status local files
     #
     - name: Merge all the ansible node bkup status files
       shell: "cat /tmp/mqbackup_QM*.txt >> /tmp/bkup_status.txt"

     - name: Find files on ansible local node to be deleted
       find:
         paths: "/tmp"
         patterns: "mqbackup_QM.+.txt"
         use_regex: yes
         file_type: file
       register: local_status_files

     - name: delete all local status files
       file:
         path: "{{ item.path }}"
         state: absent
       with_items: "{{ local_status_files.files }}"

     - name: Email the backup status 
       include_role:
          name: email
       vars:
          subject: "MQ Object Backup Status Summary"
          filename: "/tmp/bkup_status.txt"
          hosts: "{{ HOST }}"
